In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf
import keras 
import matplotlib.pyplot as plt
%matplotlib inline
df=pd.read_csv(r'C:\Users\varun\Downloads\insurance_data.csv')
df.head()

age  affordibility  bought_insurance
0   22              1                 0
1   25              0                 0
2   47              1                 1
3   52              0                 0
4   46              1                 1

In [2]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(df[['age','affordibility']],df.bought_insurance,test_size=0.2,random_state=25)

In [3]:
x_train.shape

(22, 2)

In [4]:
len(x_train)

22

In [69]:
y_train

0     0
13    0
6     0
17    1
24    1
19    0
25    1
16    1
20    0
3     0
7     1
1     0
5     1
27    0
8     1
18    0
12    0
23    1
22    1
15    1
26    0
4     1
Name: bought_insurance, dtype: int64

In [6]:
len(x_test)

6

In [7]:
len(y_test)

6

In [70]:
y_test
print(y_test.shape)
print(y_train.shape)

(6,)
(22,)


#now converting my age data into 0 to 1 
#so to do it I have to divide my age section by 100 to make sure my data lies btw 0 to 1 and after that it can be scaled and ml or dl can be implemented accurately.

In [9]:
x_train

age  affordibility
0    22              1
13   29              0
6    55              0
17   58              1
24   50              1
19   18              1
25   54              1
16   25              0
20   21              1
3    52              0
7    60              0
1    25              0
5    56              1
27   46              1
8    62              1
18   19              0
12   27              0
23   45              1
22   40              1
15   55              1
26   23              1
4    46              1

In [10]:
x_test

age  affordibility
2    47              1
10   18              1
21   26              0
11   28              1
14   49              1
9    61              1

In [11]:
x_train_scaled = x_train.copy()
x_train_scaled['age'] = x_train_scaled['age'] / 100
x_test_scaled=x_test.copy()
x_test_scaled['age'] = x_test_scaled['age'] / 100

In [12]:
x_train_scaled

age  affordibility
0   0.22              1
13  0.29              0
6   0.55              0
17  0.58              1
24  0.50              1
19  0.18              1
25  0.54              1
16  0.25              0
20  0.21              1
3   0.52              0
7   0.60              0
1   0.25              0
5   0.56              1
27  0.46              1
8   0.62              1
18  0.19              0
12  0.27              0
23  0.45              1
22  0.40              1
15  0.55              1
26  0.23              1
4   0.46              1

In [13]:
x_test_scaled

age  affordibility
2   0.47              1
10  0.18              1
21  0.26              0
11  0.28              1
14  0.49              1
9   0.61              1

In [14]:
# build an neural network
# here kernel initializer is the weights of the input and bias initiazier is the value in the equation. i.e. y=mx+c+b whhere b is bias initailizer
model=keras.Sequential([keras.layers.Dense(1,input_shape=(2, ),activation='sigmoid', kernel_initializer='ones',bias_initializer='zeros')])
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
model.fit(x_train_scaled,y_train,epochs=5000)

Epoch 1/5000


C:\Users\varun\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\keras\src\layers\core\dense.py:85: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 854ms/step - accuracy: 0.5000 - loss: 0.7113
Epoch 2/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.5000 - loss: 0.7110
Epoch 3/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.5000 - loss: 0.7106
Epoch 4/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.5000 - loss: 0.7102
Epoch 5/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.5000 - loss: 0.7098
Epoch 6/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.5000 - loss: 0.7094
Epoch 7/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.5000 - loss: 0.7091
Epoch 8/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.5000 - loss: 0.7087
Epoch 9/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.5000 - loss: 0.7083
Epoch 10/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.5000 - loss: 0.7079
Epoch 11/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.5000 - loss: 0.7076
Epoch 12/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - accuracy: 0.5000 - lo

IOPub message rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_msg_rate_limit`.

Current values:
ServerApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
ServerApp.rate_limit_window=3.0 (secs)



In [15]:
model.evaluate(x_train_scaled,y_train)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 207ms/step - accuracy: 0.9091 - loss: 0.4631


[0.463053822517395, 0.9090909361839294]

In [16]:
model.predict(x_train_scaled)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step


array([[0.4033175 ],
       [0.1906098 ],
       [0.46748886],
       [0.80694014],
       [0.7360194 ],
       [0.3556957 ],
       [0.77343595],
       [0.16131353],
       [0.39120027],
       [0.42995027],
       [0.53066516],
       [0.16131353],
       [0.7906805 ],
       [0.6948614 ],
       [0.836537  ],
       [0.1243203 ],
       [0.17548092],
       [0.6840263 ],
       [0.6269827 ],
       [0.7821814 ],
       [0.4155538 ],
       [0.6948614 ]], dtype=float32)

In [18]:
# to know weights of the input file
# we will have to use model.get_weights() func.
coef,intercept=model.get_weights()
# here coef acts as w1 and w2 & intercept acts as biased weight.

In [19]:
coef

array([[5.060863 ],
       [1.4086521]], dtype=float32)

In [20]:
intercept

array([-2.913703], dtype=float32)

In [21]:
#implementing same method by using scratching python and do it without the use of tensorflow.

In [40]:
def sigmoid(x):
    import math
    return 1/(1+math.exp(-x))
sigmoid(5)

0.9933071490757153

In [43]:
def prediction_function(age,affordibility):
    
    weighted_sum= coef[0]*age+coef[0]*affordibility+intercept
    return sigmoid(weighted_sum)
    #return sigmoid because we are using sigmoid function equation to get our o/p.     

In [30]:
#calling prediciton function to check my output wheter it is suitable to my keras and tensorflow output or not.

In [45]:
prediction_function(.47,1)

C:\Users\varun\AppData\Local\Temp\ipykernel_18204\2563032672.py:3: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  return 1/(1+math.exp(-x))


0.9892895315648974

In [46]:
prediction_function(.18,1)

C:\Users\varun\AppData\Local\Temp\ipykernel_18204\2563032672.py:3: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  return 1/(1+math.exp(-x))


0.9551316047603186

In [54]:
def log_loss(y_true,y_predicted):
    epsilon=1e-15
    y_predicted_new=[max(i,epsilon) for i in y_predicted]
    y_predicted_new=[min(i,epsilon) for i in y_predicted_new]
    y_predicted_new=np.array(y_predicted_new)
    return -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

In [55]:
# now using sigmoid function for numpy
def sigmoid_numpy(x):
    return 1/(1+np.exp(-x))
sigmoid_numpy(np.array([12,0,1]))

array([0.99999386, 0.5       , 0.73105858])

In [65]:
#y_true is bought_insurance column
    #w1 and w2 are weights of the i/p and bias is intercept of the linear eq.
    #we can use loss thresold in the gradient parameter when we want to stop of gradient fun working after defining a particualr loss 
    # gradient_descent(age,affordibility,y_true,epochs,loos_thresold=no. you wwant to make it stop)
    

In [66]:
def gradient_descent(age, affordability, y_true, epochs, loss_thresold):
    w1 = w2 = 1
    bias = 0
    rate = 0.5
    n = len(age)
    for i in range(epochs):
        weighted_sum = w1 * age + w2 * affordability + bias
        y_predicted = sigmoid_numpy(weighted_sum)
        loss = log_loss(y_true, y_predicted)

        w1d = (1/n)*np.dot(np.transpose(age),(y_predicted-y_true)) 
        w2d = (1/n)*np.dot(np.transpose(affordability),(y_predicted-y_true)) 

        bias_d = np.mean(y_predicted-y_true)
        w1 = w1 - rate * w1d
        w2 = w2 - rate * w2d
        bias = bias - rate * bias_d

        print (f'Epoch:{i}, w1:{w1}, w2:{w2}, bias:{bias}, loss:{loss}')

        if loss<=loss_thresold:
            break

    return w1, w2, bias

In [68]:
gradient_descent(x_train_scaled['age'],x_train_scaled['affordibility'],y_train,1000, 0.4631)

Epoch:0, w1:0.974907633470177, w2:0.948348125394529, bias:-0.11341867736368583, loss:17.26938819745534
Epoch:1, w1:0.9556229728273669, w2:0.9058873696677865, bias:-0.2122349122718517, loss:17.26938819745534
Epoch:2, w1:0.9416488476693794, w2:0.8719790823960313, bias:-0.2977578997796538, loss:17.26938819745534
Epoch:3, w1:0.9323916996249162, w2:0.8457541517722915, bias:-0.3715094724003511, loss:17.26938819745534
Epoch:4, w1:0.9272267472726993, w2:0.8262362885332687, bias:-0.43506643026891584, loss:17.26938819745534
Epoch:5, w1:0.9255469396815343, w2:0.8124402814952774, bias:-0.48994490058938817, loss:17.26938819745534
Epoch:6, w1:0.9267936114129968, w2:0.8034375029757677, bias:-0.5375299543522853, loss:17.26938819745534
Epoch:7, w1:0.93047170420295, w2:0.7983920007454487, bias:-0.5790424270894963, loss:17.26938819745534
Epoch:8, w1:0.9361540784567942, w2:0.7965748796787705, bias:-0.6155315088627655, loss:17.26938819745534
Epoch:9, w1:0.9434791243557357, w2:0.7973647616854131, bias:-0.64

(8.270239516056172, 1.6332228396255535, -4.425953608965705)